### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by DannyCork** [kochrt/timeline-maker#1]
It would be nice if one was able to assign a specific colour to an entry

perhaps something like this
```
red 09/2019: Hawaii with Google
blue 12/20/2019-12/22/2019: Train from Seattle to Chicago
red 12/2019: Christmas at home, Dad to hospital
```

**Comment by kochrt** [comment]
I think I'm more inclined to include something like tags, and then you can specify the color per tag?

```
!trip: red
!personal: blue

09/2019: Hawaii with Google !trip
12/20/2019-12/22/2019: Train from Seattle to Chicago !personal
```

This would allow there to be a key displayed somewhere. I would also, at least initially, probably only support one tag per event.

**Comment by DannyCork** [comment]
yeah, tags sound like a good approach, looking forward to it!
