### ISSUE TITLE
Help me use your vscode extension

### ISSUE THREAD

**Issue by EduardRotaru** [kochrt/timeline-maker#115]
Alright I created a file with the extension .mw but it doesn't show a calendar or a map, 

I wrote this in the file:  

`Title: Personal goals

Dec 7 - Dec 8: asdasdsa `

Vscode recognize that but it doesn't show anything else

**Comment by kochrt** [comment]
Is there a preview button in the top right corner?

<img width="287" alt="Screen Shot 2023-04-12 at 6 20 13 PM" src="https://user-images.githubusercontent.com/10823320/231598917-aff02a04-ce1c-4753-acb5-d466f72dbd29.png">

**Comment by EduardRotaru** [comment]
Yes, I found it, it was in the very top right. Thank you very much.
