### ISSUE TITLE
Please add tag 'gantt' to the project.

### ISSUE THREAD

**Issue by imesha10** [kochrt/timeline-maker#116]
I was looking for a decent self hosted gantt chart for personal use that works on windows for the last few months putting alot of effort. I almost gave up looking. This is what I've been looking for. It's amazing! 🎉🎉🎉

The way I was looking for was seraching by the tags gantt, gantt-chart, project management so I never found this repo.

It might help others like me to find this repo if you add this to the tags.

**Comment by kochrt** [comment]
Done, thanks for the suggestion!
