### ISSUE TITLE
Search for TAGs 

### ISSUE THREAD

**Issue by pitecantropo** [kochrt/timeline-maker#123]
Hi,

Any chance to add a search for the filter box?
Would be useful for really big timelines with a huge amount of tags.

Thanks in advance!

**Comment by kochrt** [comment]
Done, can you try it out and let me know if it works ok? 

I would be interested in seeing some of your markwhen documents if you wouldn't mind sharing them! It would be helpful to me to see what heavy users are using it for/how performance is for really big timelines etc. I can only come up with contrived examples.
