### ISSUE TITLE
View link opens greyscale version

### ISSUE THREAD

**Issue by emeyedeejay** [kochrt/timeline-maker#124]
What an amazing tool! Love it.

When I copy a view URL and open it in both Edge and Chrome the view is greyscale - is this right?

(Except for that one orange line ... wierd!)

![image](https://github.com/mark-when/markwhen/assets/8543879/9f461ec3-10ff-466b-9818-01d3c6778a6f)

**Comment by kochrt** [comment]
Fixed by https://github.com/mark-when/timeline/commit/78718e7e47a7be9d4ed8eab7b5320bb423087e8d
