### ISSUE TITLE
The Markwhen VS Code extension is nowhere to be found

### ISSUE THREAD

**Issue by asitemade4u** [kochrt/timeline-maker#125]
Hi,
I am trying to find the Markwhen extension in VS Code, also tried to add the search string in the palette (using Ctrl + P): in vain, the extension is nowhere to be found.
I am using VS Code OSS on Manjaro Linux, last version.
Please help,
Best,
Stephen

**Comment by kochrt** [comment]
Is it not [here](https://marketplace.visualstudio.com/items?itemName=Markwhen.markwhen)?

**Comment by asitemade4u** [comment]
Thanks for the answer.
There was no way to install it from the market-place.
The only way it worked was by downloading the vsix extension file and install it manually.
Problem solved!

**Comment by roaldarbol** [comment]
Just an added comment to this (maybe worth reopening). For VSCode alternatives, such as VSCodium and possibly also Code OSS, uses the [OpenVSX registry](https://open-vsx.org/) for extensions, so it is maybe worth it to also add the extension there (see [here for a guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)).
