### ISSUE TITLE
Feature request: Allow specifying key dates that show vertical bar like "now" bar

### ISSUE THREAD

**Issue by felixr** [kochrt/timeline-maker#126]
Especially in project planning you might have key dates that you want to highlight and e.g. identify tasks that run past that date. For this it would be nice to be able to specify dates that are represented as vertical bars similarly to the now bar that shows where we are at today.

Here a very crude mock of what I have in mind: 
![2023-06-19_13-00](https://github.com/mark-when/markwhen/assets/1200407/e84a1dc9-0347-4ba7-a918-44855e69c247)

Note this is possibly somewhat related to #24 if you want to be able to use the key dates in the specification of tasks.

---

Also want to say that markwhen is really beautifully made and a joy to use. Great work!

**Comment by kochrt** [comment]
Apparently I haven't (yet) documented this anywhere (I thought I did) but if you make an event and add the `#era` or `#milestone` tag it will add a vertical bar like you're describing.

**Comment by felixr** [comment]
Neat! Can confirm that this works. Thank you!

![2023-06-19_14-50](https://github.com/mark-when/markwhen/assets/1200407/f8e59fe4-4988-4cf4-a88b-ac088dd928db)
