### ISSUE TITLE
[Feature request] Continuous vertical line for custom date

### ISSUE THREAD

**Issue by JakobFerdinand** [kochrt/timeline-maker#128]
Hello,

It would be great to have the possibility to add vertical lines through the entire timeline graph at a custom timestamp.
Exactly like the vertical line that shows the current date, just for custom dates.

**Comment by kochrt** [comment]
Try the `#era` or `#milestone` tag on an event, it gives a vertical line like you're describing

**Comment by JakobFerdinand** [comment]
Ah great! That´s what I needed! 👍🏼
