### ISSUE TITLE
VS Code extension update 1.4.0 broke visualization. 

### ISSUE THREAD

**Issue by Thiousi** [kochrt/timeline-maker#134]
12 errors at runtime. See screenshot.
No Changelog published on the new version. Reverting to 1.3.1 fixed it.
<img width="296" alt="MicrosoftTeams-image" src="https://github.com/mark-when/markwhen/assets/4822666/868de207-2865-47f1-b2d6-5dff79160da3">

**Comment by kochrt** [comment]
I just pushed 1.4.1, can you try that and see if it fixes things?

**Comment by Thiousi** [comment]
Thanks for the quick fix. I confirm I don't have the issue anymore with 1.4.1
